#!/bin/bash

# Replace decimal points with commas in all exercise files

perseus_dir="$1"

for dir in "$perseus_dir"/*; do
    if [ -d "$dir" ];
    then
    	for file in "$dir"/*; do
    	if [ -f "$file" ] && [[ "$file" == *".json" ]] && ! [[ "$file" == *"exercise.json" ]]; then
    		# sed -i -r 's///g' "$file"
    		sed -i -r 's/\$([[:digit:]]+)\.([[:digit:]]+)/\$\1\,\2/g' "$file"
    		sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+)\$/\1\,\2\$/g' "$file"
    		sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+)\=/\1\,\2\=/g' "$file"
    		sed -i -r 's/\$\\\\Huge\.\$/\$\\\\Huge\,\$/g' "$file"
            
    		# sed -i -r 's/\$\\\\((?:small|Huge|Large)) ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\\1 \2\,\3/g' "$file"
            sed -i -r 's/\$\\\\small ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\small \1\,\2/g' "$file"
            sed -i -r 's/\$\\\\Huge ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\Huge \1\,\2/g' "$file"
            sed -i -r 's/\$\\\\Large ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\Large \1\,\2/g' "$file"

            sed -i -r 's/\$\\\\small([[:digit:]]+)\.([[:digit:]]+)/\$\\\\small\1\,\2/g' "$file"
            sed -i -r 's/\$\\\\Huge([[:digit:]]+)\.([[:digit:]]+)/\$\\\\Huge\1\,\2/g' "$file"
            sed -i -r 's/\$\\\\Large([[:digit:]]+)\.([[:digit:]]+)/\$\\\\Large\1\,\2/g' "$file"
            
    		# sed -i -r 's/\$\\\\((?:small|Huge|Large))\{ ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\\1\{ \2\,\3/g' "$file"
            sed -i -r 's/\$\\\\small\{ ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\small\{ \1\,\2/g' "$file"
            sed -i -r 's/\$\\\\Huge\{ ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\Huge\{ \1\,\2/g' "$file"
            sed -i -r 's/\$\\\\Large\{ ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\Large\{ \1\,\2/g' "$file"
            sed -i -r 's/\$\\\\large\{ ([[:digit:]]+)\.([[:digit:]]+)/\$\\\\large\{ \1\,\2/g' "$file"

            sed -i -r 's/\\\\small\{ ([[:digit:]]+)\.([[:digit:]]+)/\\\\small\{ \1\,\2/g' "$file"
            sed -i -r 's/\\\\Huge\{ ([[:digit:]]+)\.([[:digit:]]+)/\\\\Huge\{ \1\,\2/g' "$file"
            sed -i -r 's/\\\\Large\{ ([[:digit:]]+)\.([[:digit:]]+)/\\\\Large\{ \1\,\2/g' "$file"
            sed -i -r 's/\\\\large\{ ([[:digit:]]+)\.([[:digit:]]+)/\\\\large\{ \1\,\2/g' "$file"

            sed -i -r 's/\$\\\\small\{([[:digit:]]+)\.([[:digit:]]+)/\$\\\\small\{\1\,\2/g' "$file"
            sed -i -r 's/\$\\\\Huge\{([[:digit:]]+)\.([[:digit:]]+)/\$\\\\Huge\{\1\,\2/g' "$file"
            sed -i -r 's/\$\\\\Large\{([[:digit:]]+)\.([[:digit:]]+)/\$\\\\Large\{\1\,\2/g' "$file"
            sed -i -r 's/\$\\\\large\{([[:digit:]]+)\.([[:digit:]]+)/\$\\\\large\{\1\,\2/g' "$file"

            sed -i -r 's/\\\\small\{([[:digit:]]+)\.([[:digit:]]+)/\\\\small\{\1\,\2/g' "$file"
            sed -i -r 's/\\\\Huge\{([[:digit:]]+)\.([[:digit:]]+)/\\\\Huge\{\1\,\2/g' "$file"
            sed -i -r 's/\\\\Large\{([[:digit:]]+)\.([[:digit:]]+)/\\\\Large\{\1\,\2/g' "$file"
            sed -i -r 's/\\\\large\{([[:digit:]]+)\.([[:digit:]]+)/\\\\large\{\1\,\2/g' "$file"

    		# sed -i -r  's/\\\\((?:purple|pink|green|red|blue|teal|gold|purpleD|pinkD|greenD|redD|blueD|tealD|goldD))\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\\1\{\+\2\,\3\}/g' "$file"
            sed -i -r  's/\\\\purple\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\purple\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\pink\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\pink\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\green\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\green\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\red\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\red\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\blue\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\blue\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\teal\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\teal\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\gold\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\gold\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\purpleD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\purpleD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\purple\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\purpleD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\pinkD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\pinkD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\greenD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\greenD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\redD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\redD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\blueD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\blueD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\tealD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\tealD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\goldD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\goldD\{\+\1\,\2\}/g' "$file"

            sed -i -r  's/\\\\purpleC\{\-([[:digit:]]+)\.([[:digit:]]+)\}/\\\\purpleC\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\pinkC\{\-([[:digit:]]+)\.([[:digit:]]+)\}/\\\\pinkC\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\greenC\{\-([[:digit:]]+)\.([[:digit:]]+)\}/\\\\greenC\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\redC\{\-([[:digit:]]+)\.([[:digit:]]+)\}/\\\\redC\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\blueC\{\-([[:digit:]]+)\.([[:digit:]]+)\}/\\\\blueC\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\tealC\{\-([[:digit:]]+)\.([[:digit:]]+)\}/\\\\tealC\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\goldC\{\-([[:digit:]]+)\.([[:digit:]]+)\}/\\\\goldC\{\-\1\,\2\}/g' "$file"

            sed -i -r  's/purpleC\{\+([[:digit:]]+)\.([[:digit:]]+)\}/purpleC\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/pinkC\{\+([[:digit:]]+)\.([[:digit:]]+)\}/pinkC\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/greenC\{\+([[:digit:]]+)\.([[:digit:]]+)\}/greenC\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/redC\{\+([[:digit:]]+)\.([[:digit:]]+)\}/redC\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/blueC\{\+([[:digit:]]+)\.([[:digit:]]+)\}/blueC\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/tealC\{\+([[:digit:]]+)\.([[:digit:]]+)\}/tealC\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/goldC\{\+([[:digit:]]+)\.([[:digit:]]+)\}/goldC\{\+\1\,\2\}/g' "$file"

            sed -i -r  's/purpleC\{([[:digit:]]+)\.([[:digit:]]+)\}/purpleC\{\1\,\2\}/g' "$file"
            sed -i -r  's/pinkC\{([[:digit:]]+)\.([[:digit:]]+)\}/pinkC\{\1\,\2\}/g' "$file"
            sed -i -r  's/greenC\{([[:digit:]]+)\.([[:digit:]]+)\}/greenC\{\1\,\2\}/g' "$file"
            sed -i -r  's/redC\{([[:digit:]]+)\.([[:digit:]]+)\}/redC\{\1\,\2\}/g' "$file"
            sed -i -r  's/blueC\{([[:digit:]]+)\.([[:digit:]]+)\}/blueC\{\1\,\2\}/g' "$file"
            sed -i -r  's/tealC\{([[:digit:]]+)\.([[:digit:]]+)\}/tealC\{\1\,\2\}/g' "$file"
            sed -i -r  's/goldC\{([[:digit:]]+)\.([[:digit:]]+)\}/goldC\{\1\,\2\}/g' "$file"

            sed -i -r  's/purple\{\+([[:digit:]]+)\.([[:digit:]]+)\}/purple\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/pink\{\+([[:digit:]]+)\.([[:digit:]]+)\}/pink\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/green\{\+([[:digit:]]+)\.([[:digit:]]+)\}/green\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/red\{\+([[:digit:]]+)\.([[:digit:]]+)\}/red\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/blue\{\+([[:digit:]]+)\.([[:digit:]]+)\}/blue\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/teal\{\+([[:digit:]]+)\.([[:digit:]]+)\}/teal\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/gold\{\+([[:digit:]]+)\.([[:digit:]]+)\}/gold\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/purpleD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/purpleD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/pinkD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/pinkD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/greenD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/greenD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/redD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/redD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/blueD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/blueD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/tealD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/tealD\{\+\1\,\2\}/g' "$file"
            sed -i -r  's/goldD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/goldD\{\+\1\,\2\}/g' "$file"


            sed -i -r  's/purple\{\-([[:digit:]]+)\.([[:digit:]]+)\}/purple\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/pink\{\-([[:digit:]]+)\.([[:digit:]]+)\}/pink\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/green\{\-([[:digit:]]+)\.([[:digit:]]+)\}/green\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/red\{\-([[:digit:]]+)\.([[:digit:]]+)\}/red\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/blue\{\-([[:digit:]]+)\.([[:digit:]]+)\}/blue\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/teal\{\-([[:digit:]]+)\.([[:digit:]]+)\}/teal\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/gold\{\-([[:digit:]]+)\.([[:digit:]]+)\}/gold\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/purpleD\{\-([[:digit:]]+)\.([[:digit:]]+)\}/purpleD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/pinkD\{\-([[:digit:]]+)\.([[:digit:]]+)\}/pinkD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/greenD\{\-([[:digit:]]+)\.([[:digit:]]+)\}/greenD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/redD\{\-([[:digit:]]+)\.([[:digit:]]+)\}/redD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/blueD\{\-([[:digit:]]+)\.([[:digit:]]+)\}/blueD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/tealD\{\-([[:digit:]]+)\.([[:digit:]]+)\}/tealD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/goldD\{\-([[:digit:]]+)\.([[:digit:]]+)\}/goldD\{\-\1\,\2\}/g' "$file"

            sed -i -r  's/purple\{([[:digit:]]+)\.([[:digit:]]+)\}/purple\{\1\,\2\}/g' "$file"
            sed -i -r  's/pink\{([[:digit:]]+)\.([[:digit:]]+)\}/pink\{\1\,\2\}/g' "$file"
            sed -i -r  's/green\{([[:digit:]]+)\.([[:digit:]]+)\}/green\{\1\,\2\}/g' "$file"
            sed -i -r  's/red\{([[:digit:]]+)\.([[:digit:]]+)\}/red\{\1\,\2\}/g' "$file"
            sed -i -r  's/blue\{([[:digit:]]+)\.([[:digit:]]+)\}/blue\{\1\,\2\}/g' "$file"
            sed -i -r  's/teal\{([[:digit:]]+)\.([[:digit:]]+)\}/teal\{\1\,\2\}/g' "$file"
            sed -i -r  's/gold\{([[:digit:]]+)\.([[:digit:]]+)\}/gold\{\1\,\2\}/g' "$file"
            sed -i -r  's/purpleD\{([[:digit:]]+)\.([[:digit:]]+)\}/purpleD\{\1\,\2\}/g' "$file"
            sed -i -r  's/pinkD\{([[:digit:]]+)\.([[:digit:]]+)\}/pinkD\{\1\,\2\}/g' "$file"
            sed -i -r  's/greenD\{([[:digit:]]+)\.([[:digit:]]+)\}/greenD\{\1\,\2\}/g' "$file"
            sed -i -r  's/redD\{([[:digit:]]+)\.([[:digit:]]+)\}/redD\{\1\,\2\}/g' "$file"
            sed -i -r  's/blueD\{([[:digit:]]+)\.([[:digit:]]+)\}/blueD\{\1\,\2\}/g' "$file"
            sed -i -r  's/tealD\{([[:digit:]]+)\.([[:digit:]]+)\}/tealD\{\1\,\2\}/g' "$file"
            sed -i -r  's/goldD\{([[:digit:]]+)\.([[:digit:]]+)\}/goldD\{\1\,\2\}/g' "$file"
    		
            # sed -i -r  's/\\\\((?:purple|pink|green|red|blue|teal|gold|purpleD|pinkD|greenD|redD|blueD|tealD|goldD))\{\-([[:digit:]]+)\.([[:digit:]]+)\}/\\\\\1\{\-\2\,\3\}/g' "$file"
            sed -i -r  's/\\\\purple\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\purple\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\pink\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\pink\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\green\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\green\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\red\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\red\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\blue\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\blue\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\teal\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\teal\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\gold\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\gold\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\purpleD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\purpleD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\pinkD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\pinkD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\greenD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\greenD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\redD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\redD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\blueD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\blueD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\tealD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\tealD\{\-\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\goldD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\goldD\{\-\1\,\2\}/g' "$file"

    		# sed -i -r  's/\\\\((?:purple|pink|green|red|blue|teal|gold|purpleD|pinkD|greenD|redD|blueD|tealD|goldD))\{([[:digit:]]+)\.([[:digit:]]+)\}/\\\\\1\{\2\,\3\}/g' "$file"
            
            sed -i -r  's/\\\\purple\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\purple\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\pink\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\pink\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\green\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\green\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\red\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\red\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\blue\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\blue\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\teal\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\teal\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\gold\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\gold\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\purpleD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\purpleD\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\pinkD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\pinkD\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\greenD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\greenD\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\redD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\redD\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\blueD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\blueD\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\tealD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\tealD\{\1\,\2\}/g' "$file"
            sed -i -r  's/\\\\goldD\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\goldD\{\1\,\2\}/g' "$file"





            #######
            ###################
            ####################################
            ######################################################
            # Same regexes as above, but without closing curly brace {

            # sed -i -r  's/\\\\((?:purple|pink|green|red|blue|teal|gold|purpleD|pinkD|greenD|redD|blueD|tealD|goldD))\{\+([[:digit:]]+)\.([[:digit:]]+)\}/\\\\\1\{\+\2\,\3\}/g' "$file"
            sed -i -r  's/\\\\purple\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\purple\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\pink\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\pink\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\green\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\green\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\red\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\red\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\blue\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\blue\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\teal\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\teal\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\gold\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\gold\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\purpleD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\purpleD\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\purple\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\purpleD\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\pinkD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\pinkD\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\greenD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\greenD\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\redD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\redD\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\blueD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\blueD\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\tealD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\tealD\{\+\1\,\2/g' "$file"
            sed -i -r  's/\\\\goldD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\goldD\{\+\1\,\2/g' "$file"

            sed -i -r  's/\\\\purpleC\{\-([[:digit:]]+)\.([[:digit:]]+)/\\\\purpleC\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\pinkC\{\-([[:digit:]]+)\.([[:digit:]]+)/\\\\pinkC\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\greenC\{\-([[:digit:]]+)\.([[:digit:]]+)/\\\\greenC\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\redC\{\-([[:digit:]]+)\.([[:digit:]]+)/\\\\redC\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\blueC\{\-([[:digit:]]+)\.([[:digit:]]+)/\\\\blueC\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\tealC\{\-([[:digit:]]+)\.([[:digit:]]+)/\\\\tealC\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\goldC\{\-([[:digit:]]+)\.([[:digit:]]+)/\\\\goldC\{\-\1\,\2/g' "$file"

            sed -i -r  's/purpleC\{\+([[:digit:]]+)\.([[:digit:]]+)/purpleC\{\+\1\,\2/g' "$file"
            sed -i -r  's/pinkC\{\+([[:digit:]]+)\.([[:digit:]]+)/pinkC\{\+\1\,\2/g' "$file"
            sed -i -r  's/greenC\{\+([[:digit:]]+)\.([[:digit:]]+)/greenC\{\+\1\,\2/g' "$file"
            sed -i -r  's/redC\{\+([[:digit:]]+)\.([[:digit:]]+)/redC\{\+\1\,\2/g' "$file"
            sed -i -r  's/blueC\{\+([[:digit:]]+)\.([[:digit:]]+)/blueC\{\+\1\,\2/g' "$file"
            sed -i -r  's/tealC\{\+([[:digit:]]+)\.([[:digit:]]+)/tealC\{\+\1\,\2/g' "$file"
            sed -i -r  's/goldC\{\+([[:digit:]]+)\.([[:digit:]]+)/goldC\{\+\1\,\2/g' "$file"

            sed -i -r  's/purpleC\{([[:digit:]]+)\.([[:digit:]]+)/purpleC\{\1\,\2/g' "$file"
            sed -i -r  's/pinkC\{([[:digit:]]+)\.([[:digit:]]+)/pinkC\{\1\,\2/g' "$file"
            sed -i -r  's/greenC\{([[:digit:]]+)\.([[:digit:]]+)/greenC\{\1\,\2/g' "$file"
            sed -i -r  's/redC\{([[:digit:]]+)\.([[:digit:]]+)/redC\{\1\,\2/g' "$file"
            sed -i -r  's/blueC\{([[:digit:]]+)\.([[:digit:]]+)/blueC\{\1\,\2/g' "$file"
            sed -i -r  's/tealC\{([[:digit:]]+)\.([[:digit:]]+)/tealC\{\1\,\2/g' "$file"
            sed -i -r  's/goldC\{([[:digit:]]+)\.([[:digit:]]+)/goldC\{\1\,\2/g' "$file"

            sed -i -r  's/purple\{\+([[:digit:]]+)\.([[:digit:]]+)/purple\{\+\1\,\2/g' "$file"
            sed -i -r  's/pink\{\+([[:digit:]]+)\.([[:digit:]]+)/pink\{\+\1\,\2/g' "$file"
            sed -i -r  's/green\{\+([[:digit:]]+)\.([[:digit:]]+)/green\{\+\1\,\2/g' "$file"
            sed -i -r  's/red\{\+([[:digit:]]+)\.([[:digit:]]+)/red\{\+\1\,\2/g' "$file"
            sed -i -r  's/blue\{\+([[:digit:]]+)\.([[:digit:]]+)/blue\{\+\1\,\2/g' "$file"
            sed -i -r  's/teal\{\+([[:digit:]]+)\.([[:digit:]]+)/teal\{\+\1\,\2/g' "$file"
            sed -i -r  's/gold\{\+([[:digit:]]+)\.([[:digit:]]+)/gold\{\+\1\,\2/g' "$file"
            sed -i -r  's/purpleD\{\+([[:digit:]]+)\.([[:digit:]]+)/purpleD\{\+\1\,\2/g' "$file"
            sed -i -r  's/pinkD\{\+([[:digit:]]+)\.([[:digit:]]+)/pinkD\{\+\1\,\2/g' "$file"
            sed -i -r  's/greenD\{\+([[:digit:]]+)\.([[:digit:]]+)/greenD\{\+\1\,\2/g' "$file"
            sed -i -r  's/redD\{\+([[:digit:]]+)\.([[:digit:]]+)/redD\{\+\1\,\2/g' "$file"
            sed -i -r  's/blueD\{\+([[:digit:]]+)\.([[:digit:]]+)/blueD\{\+\1\,\2/g' "$file"
            sed -i -r  's/tealD\{\+([[:digit:]]+)\.([[:digit:]]+)/tealD\{\+\1\,\2/g' "$file"
            sed -i -r  's/goldD\{\+([[:digit:]]+)\.([[:digit:]]+)/goldD\{\+\1\,\2/g' "$file"


            sed -i -r  's/purple\{\-([[:digit:]]+)\.([[:digit:]]+)/purple\{\-\1\,\2/g' "$file"
            sed -i -r  's/pink\{\-([[:digit:]]+)\.([[:digit:]]+)/pink\{\-\1\,\2/g' "$file"
            sed -i -r  's/green\{\-([[:digit:]]+)\.([[:digit:]]+)/green\{\-\1\,\2/g' "$file"
            sed -i -r  's/red\{\-([[:digit:]]+)\.([[:digit:]]+)/red\{\-\1\,\2/g' "$file"
            sed -i -r  's/blue\{\-([[:digit:]]+)\.([[:digit:]]+)/blue\{\-\1\,\2/g' "$file"
            sed -i -r  's/teal\{\-([[:digit:]]+)\.([[:digit:]]+)/teal\{\-\1\,\2/g' "$file"
            sed -i -r  's/gold\{\-([[:digit:]]+)\.([[:digit:]]+)/gold\{\-\1\,\2/g' "$file"
            sed -i -r  's/purpleD\{\-([[:digit:]]+)\.([[:digit:]]+)/purpleD\{\-\1\,\2/g' "$file"
            sed -i -r  's/pinkD\{\-([[:digit:]]+)\.([[:digit:]]+)/pinkD\{\-\1\,\2/g' "$file"
            sed -i -r  's/greenD\{\-([[:digit:]]+)\.([[:digit:]]+)/greenD\{\-\1\,\2/g' "$file"
            sed -i -r  's/redD\{\-([[:digit:]]+)\.([[:digit:]]+)/redD\{\-\1\,\2/g' "$file"
            sed -i -r  's/blueD\{\-([[:digit:]]+)\.([[:digit:]]+)/blueD\{\-\1\,\2/g' "$file"
            sed -i -r  's/tealD\{\-([[:digit:]]+)\.([[:digit:]]+)/tealD\{\-\1\,\2/g' "$file"
            sed -i -r  's/goldD\{\-([[:digit:]]+)\.([[:digit:]]+)/goldD\{\-\1\,\2/g' "$file"

            sed -i -r  's/purple\{([[:digit:]]+)\.([[:digit:]]+)/purple\{\1\,\2/g' "$file"
            sed -i -r  's/pink\{([[:digit:]]+)\.([[:digit:]]+)/pink\{\1\,\2/g' "$file"
            sed -i -r  's/green\{([[:digit:]]+)\.([[:digit:]]+)/green\{\1\,\2/g' "$file"
            sed -i -r  's/red\{([[:digit:]]+)\.([[:digit:]]+)/red\{\1\,\2/g' "$file"
            sed -i -r  's/blue\{([[:digit:]]+)\.([[:digit:]]+)/blue\{\1\,\2/g' "$file"
            sed -i -r  's/teal\{([[:digit:]]+)\.([[:digit:]]+)/teal\{\1\,\2/g' "$file"
            sed -i -r  's/gold\{([[:digit:]]+)\.([[:digit:]]+)/gold\{\1\,\2/g' "$file"
            sed -i -r  's/purpleD\{([[:digit:]]+)\.([[:digit:]]+)/purpleD\{\1\,\2/g' "$file"
            sed -i -r  's/pinkD\{([[:digit:]]+)\.([[:digit:]]+)/pinkD\{\1\,\2/g' "$file"
            sed -i -r  's/greenD\{([[:digit:]]+)\.([[:digit:]]+)/greenD\{\1\,\2/g' "$file"
            sed -i -r  's/redD\{([[:digit:]]+)\.([[:digit:]]+)/redD\{\1\,\2/g' "$file"
            sed -i -r  's/blueD\{([[:digit:]]+)\.([[:digit:]]+)/blueD\{\1\,\2/g' "$file"
            sed -i -r  's/tealD\{([[:digit:]]+)\.([[:digit:]]+)/tealD\{\1\,\2/g' "$file"
            sed -i -r  's/goldD\{([[:digit:]]+)\.([[:digit:]]+)/goldD\{\1\,\2/g' "$file"
            
            # sed -i -r  's/\\\\((?:purple|pink|green|red|blue|teal|gold|purpleD|pinkD|greenD|redD|blueD|tealD|goldD))\{\-([[:digit:]]+)\.([[:digit:]]+)/\\\\\1\{\-\2\,\3/g' "$file"
            sed -i -r  's/\\\\purple\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\purple\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\pink\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\pink\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\green\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\green\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\red\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\red\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\blue\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\blue\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\teal\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\teal\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\gold\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\gold\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\purpleD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\purpleD\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\pinkD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\pinkD\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\greenD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\greenD\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\redD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\redD\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\blueD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\blueD\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\tealD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\tealD\{\-\1\,\2/g' "$file"
            sed -i -r  's/\\\\goldD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\goldD\{\-\1\,\2/g' "$file"

            # sed -i -r  's/\\\\((?:purple|pink|green|red|blue|teal|gold|purpleD|pinkD|greenD|redD|blueD|tealD|goldD))\{([[:digit:]]+)\.([[:digit:]]+)/\\\\\1\{\2\,\3/g' "$file"
            
            sed -i -r  's/\\\\purple\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\purple\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\pink\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\pink\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\green\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\green\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\red\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\red\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\blue\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\blue\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\teal\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\teal\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\gold\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\gold\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\purpleD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\purpleD\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\pinkD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\pinkD\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\greenD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\greenD\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\redD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\redD\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\blueD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\blueD\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\tealD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\tealD\{\1\,\2/g' "$file"
            sed -i -r  's/\\\\goldD\{\+([[:digit:]]+)\.([[:digit:]]+)/\\\\goldD\{\1\,\2/g' "$file"



            ##################################
            ##################################################
            #############################################
            ###################################
        
    		sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+) \= \{\?\}/\1\,\2 \= \{\?\}/g' "$file"
    		sed -i -r 's/\\\\times ([[:digit:]]+)\.([[:digit:]]+)/\\\\times \1\,\2/g' "$file"
    		sed -i -r 's/\\\\phantom\{\=\}([[:digit:]]+)\.([[:digit:]]+)/\\\\phantom\{\=\}\1\,\2/g' "$file"
    		sed -i -r 's/\$\.\$/\$\,\$/g' "$file"
    		sed -i -r 's/\= ([[:digit:]]+)\.([[:digit:]]+) \}/\=  \1\,\2\}/g' "$file"
    		sed -i -r 's/\}([[:digit:]]+)\.([[:digit:]]+)\}/\}\1\,\2\}/g' "$file"
    		sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+) \\\\text/\1\,\2 \\\\text/g' "$file"
    		sed -i -r 's/\+ ([[:digit:]]+)\.([[:digit:]]+)/\+ \1\,\2/g' "$file"
    		sed -i -r 's/\- ([[:digit:]]+)\.([[:digit:]]+)/\- \1\,\2/g' "$file"
    		sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+)\+([[:digit:]]+)\.([[:digit:]]+)/\1\,\2\+\3\,\4/g' "$file"
    		sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+)\-([[:digit:]]+)\.([[:digit:]]+)/\1\,\2\-\3\,\4/g' "$file"
    		sed -i -r 's/\}\+([[:digit:]]+)\.([[:digit:]]+)/\}\+\1\,\2/g' "$file"
    		sed -i -r 's/\}\-([[:digit:]]+)\.([[:digit:]]+)/\}\-\1\,\2/g' "$file"
    		sed -i -r 's/\=([[:digit:]]+)\.([[:digit:]]+)/\=\1\,\2/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.([[:digit:]]+)/\= \1\,\2/g' "$file"


            sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+) \< ([[:digit:]]+)\.([[:digit:]]+)/\1\,\2 \< \3\,\4/g' "$file"
            sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+) \> ([[:digit:]]+)\.([[:digit:]]+)/\1\,\2 \> \3\,\4/g' "$file"
            sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+) \+ ([[:digit:]]+)\.([[:digit:]]+)/\1\,\2 \+ \3\,\4/g' "$file"
            sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+) \- ([[:digit:]]+)\.([[:digit:]]+)/\1\,\2 \- \3\,\4/g' "$file"
            sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+) \= ([[:digit:]]+)\.([[:digit:]]+)/\1\,\2 \= \3\,\4/g' "$file"
            sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+) \× ([[:digit:]]+)\.([[:digit:]]+)/\1\,\2 \× \3\,\4/g' "$file"
            sed -i -r 's/([[:digit:]]+)\.([[:digit:]]+)\×([[:digit:]]+)\.([[:digit:]]+)/\1\,\2\×\3\,\4/g' "$file"



            sed -i -r 's/\.\\\\pinkD/\,\\\\pinkD/g' "$file"
            sed -i -r 's/\.\\\\blueD/\,\\\\blueD/g' "$file"
            sed -i -r 's/\.\\\\blueD/\,\\\\blueD/g' "$file"
            sed -i -r 's/\.\\\\greenD/\,\\\\greenD/g' "$file"
            sed -i -r 's/\.\\\\redD/\,\\\\redD/g' "$file"
            sed -i -r 's/\.\\\\purpleD/\,\\\\purpleD/g' "$file"
            sed -i -r 's/\.\\\\goldD/\,\\\\goldD/g' "$file"
            sed -i -r 's/\.\\\\tealD/\,\\\\tealD/g' "$file"

            sed -i -r 's/\.\\\\pinkC/\,\\\\pinkC/g' "$file"
            sed -i -r 's/\.\\\\blueC/\,\\\\blueC/g' "$file"
            sed -i -r 's/\.\\\\greenC/\,\\\\greenC/g' "$file"
            sed -i -r 's/\.\\\\redC/\,\\\\redC/g' "$file"
            sed -i -r 's/\.\\\\purpleC/\,\\\\purpleC/g' "$file"
            sed -i -r 's/\.\\\\goldC/\,\\\\goldC/g' "$file"
            sed -i -r 's/\.\\\\tealC/\,\\\\tealC/g' "$file"

            sed -i -r 's/\.\\\\pink/\,\\\\pink/g' "$file"
            sed -i -r 's/\.\\\\blue/\,\\\\blue/g' "$file"
            sed -i -r 's/\.\\\\green/\,\\\\green/g' "$file"
            sed -i -r 's/\.\\\\red/\,\\\\red/g' "$file"
            sed -i -r 's/\.\\\\purple/\,\\\\purple/g' "$file"
            sed -i -r 's/\.\\\\gold/\,\\\\gold/g' "$file"
            sed -i -r 's/\.\\\\teal/\,\\\\teal/g' "$file"

            sed -i -r 's/\.\\\\overline/\,\\\\overline/g' "$file"

            sed -i -r 's/\= ([[:digit:]]+)\.\\\\green/\= \1\,\\\\green/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\pink/\= \1\,\\\\pink/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\blue/\= \1\,\\\\blue/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\red/\= \1\,\\\\red/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\purple/\= \1\,\\\\purple/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\gold/\= \1\,\\\\gold/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\teal/\= \1\,\\\\teal/g' "$file"

            sed -i -r 's/\= ([[:digit:]]+)\.\\\\greenD/\= \1\,\\\\greenD/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\pinkD/\= \1\,\\\\pinkD/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\blueD/\= \1\,\\\\blueD/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\redD/\= \1\,\\\\redD/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\purpleD/\= \1\,\\\\purpleD/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\goldD/\= \1\,\\\\goldD/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\tealD/\= \1\,\\\\tealD/g' "$file"

            sed -i -r 's/\= ([[:digit:]]+)\.\\\\greenC/\= \1\,\\\\greenC/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\pinkC/\= \1\,\\\\pinkC/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\blueC/\= \1\,\\\\blueC/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\redC/\= \1\,\\\\redC/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\purpleC/\= \1\,\\\\purpleC/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\goldC/\= \1\,\\\\goldC/g' "$file"
            sed -i -r 's/\= ([[:digit:]]+)\.\\\\tealC/\= \1\,\\\\tealC/g' "$file"

    		echo "$file edited"
    	fi
    done
    fi
done
